[package]
name = "azalea-derive"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = "2.0.101"
azalea-service.workspace = true
