[package]
name = "azalea-service"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
azalea-log.workspace = true

gtk.workspace = true
relm4.workspace = true
flume = "0.11.1"
tokio.workspace = true

thiserror.workspace = true
